TOP = ../..
include $(TOP)/configure/CONFIG
#ARCH = windows-x64-static
#ARCH = linux-x86_64
ARCH = $(EPICS_HOST_ARCH)
TARGETS = envPaths cdCommands dllPath.bat runIOC.bat
include $(TOP)/configure/RULES.ioc
