TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

# Note, the files in this directory were manually copied from the Fast CCD directories 
# for Linux and Windows.  The soft links for Linux were manually created.

INC += xcmclm.h
LIB_INSTALLS_WIN32 += ../os/windows-x86-static/xcmclm_x64.lib

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

