TOP = ../..
include $(TOP)/configure/CONFIG
#ARCH = linux-x86
#ARCH = linux-x86_64
#ARCH = cygwin-x86
ARCH = $(EPICS_HOST_ARCH)
TARGETS = envPaths dllPath.bat runIOC.bat 
include $(TOP)/configure/RULES.ioc
